apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090  # Internal port for Prometheus
      targetPort: 9090
      nodePort: 32001  # NodePort to access Prometheus
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
spec:
  type: NodePort
  ports:
    - port: 80  # Default HTTP port for Grafana
      targetPort: 3000  # Port on which Grafana is running
      nodePort: 32000  # NodePort to access Grafana
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
