services:
  gateway:
    image: phadkesharanmatrixcomsec/arc-gateway:1.0-alpine
    build:
      context: .
      dockerfile: Arc.Gateway/Dockerfile
    ports:
      - "5039:8080"
    depends_on:
      - authentication
      - configuration
      - vpm
    networks:
      - arc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  authentication:
    image: phadkesharanmatrixcomsec/arc-authentication:hls-1.0-alpine
    build:
      context: .
      dockerfile: Authentication.API/Dockerfile
    ports:
      - "5174:8080"
    networks:
      - arc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  configuration:
    image: phadkesharanmatrixcomsec/arc-configuration:hls-1.0-alpine
    build:
      context: . 
      dockerfile: Configuration.API/Dockerfile
    ports:
      - "5011:8080"
    networks:
      - arc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  pushnotifications:
    image: pushnotifications
    build:
      context: .
      dockerfile: Src/PushNotifications/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8083:8083
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/Firebase-Credentials/service-account-credentials.json
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./Src/PushNotifications/Firebase-Credentials:/app/Firebase-Credentials
    networks:
      - arc-network

  arc-webclient:
    image: phadkesharanmatrixcomsec/arc-webspa:hls-1.0-slim
    build:
      context: .
      dockerfile: ./ArcClient/Dockerfile
      args:
        CONFIGURATION: production
    ports:
      - "4200:80"
    networks:
      - arc-network


  vpm:
    image: phadkesharanmatrixcomsec/arc-vpm:hls-1.0-slim
    build:
      context: . 
      dockerfile: VPM/Dockerfile
    ports:
      - "5075:8080"
    networks:
      - arc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

networks:
  arc-network:
    driver: bridge