version: '3.8'

services:
  configurationapi:
    image: configurationapi
    build:
      context: .
      dockerfile: Configuration.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5012:5012
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/mnt/c/remote_debugger:rw

  authenticationapi:
    image: authenticationapi
    build:
      context: .
      dockerfile: Authentication.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5013:5013
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/mnt/c/remote_debugger:rw



volumes:
  debug_data:
