# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  configurationapi:
    image: configurationapi
    build:
      context: .
      dockerfile: Configuration.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5012:5012
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw

  authenticationapi:
    image: authenticationapi
    build:
      context: .
      dockerfile: Authentication.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5013:5013
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
