services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ConfigDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - arc-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - "./themes/keycloak:/opt/keycloak/themes/"
      - "./keycloak-email-authenticator:/opt/keycloak/providers/"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=ConfigDb
      - DB_USER=postgres
      - DB_PASSWORD=admin
    networks:
      - arc-network

  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.27.79
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    restart: unless-stopped
    networks:
      - arc-network

volumes:
  postgres_data:
  keycloak_data:

networks:
  arc-network:
    driver: bridge

# services:
  
#   postgres:
#     image: postgres:15
#     container_name: postgres-db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: ConfigDb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   keycloak:
#     container_name: keycloak
#     image: quay.io/keycloak/keycloak:latest
#     command: ["start-dev"]
#     ports:
#       - "8080:8080"
#       - "./themes/keycloak:/opt/keycloak/themes/"
#       - "./keycloak-email-authenticator:/opt/keycloak/providers/"
#     environment:
#       - KEYCLOAK_ADMIN=admin
#       - KEYCLOAK_ADMIN_PASSWORD=admin
#       - DB_VENDOR=postgres
#       - DB_ADDR=postgres
#       - DB_DATABASE=keycloak
#       - DB_USER=keycloak_user
#       - DB_PASSWORD=your_password
#     networks:
#       - arc-network

# volumes:
#   postgres_data:

# networks:
#   arc-network:
#     driver: bridge
