version: '3.8'

services:
  configurationapi:
    image: configurationapi:latest
    ports:
      - "5012:5012"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5012
    volumes:
      - configuration_data:/remote_debugger
    networks:
      - arc-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5012/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  authenticationapi:
    image: authenticationapi:latest
    ports:
      - "5013:5013"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5013
    volumes:
      - authentication_data:/remote_debugger
    networks:
      - arc-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5013/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

volumes:
  configuration_data:
  authentication_data:
networks:
  arc-network:
    external: true
