apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-api
  labels:
    app: configuration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-api
  template:
    metadata:
      labels:
        app: configuration-api
    spec:
      containers:
      - name: configuration-api
        image: jumanakj/arc-configuration:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-api
  labels:
    app: configuration-api
spec:
  selector:
    app: configuration-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
