apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
data:
  mediamtx.yml: |
    # Your custom MediaMTX configuration goes here
    logLevel: info
    logDestinations: [stdout]

    protocols: [tcp]

    # webrtcAdditionalHosts:
    #   - 172.19.0.1

    # rtspAddress:
    #   - :8554

    rtspAddress: 0.0.0.0:8554
    hlsAddress: 0.0.0.0:8888
    
    # webrtcAddress: 0.0.0.0:8889
    # hlsAddress: 0.0.0.0:8888
    # webrtcAdditionalHosts: 
    #   - 0.0.0.0

    webrtcICEServers2: 
      - url: stun:stun2.1.google.com:19302

    paths:
      # example:
      matrixcamera:
        source: rtsp://admin:admin@192.168.111.49:554/unicaststream/1


      all_others:


    # Add other configuration options as needed

