apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
  labels:
    app: mediamtx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
      - name: mediamtx
        image: matrix.local.registry:5000/mediamtx
        args: ["/mediamtx.yml"]  # Explicitly specify the config file location
        volumeMounts:
        - name: config
          mountPath: /mediamtx.yml
          subPath: mediamtx.yml
        ports:
        - containerPort: 8554
        - containerPort: 1935
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 8890
        - containerPort: 8189
        env:
        - name: MTX_PROTOCOLS
          value: "tcp"
        - name: MTX_WEBRTCADDITIONALHOSTS
          value: "172.19.0.1"
        resources:
          limits:
            cpu: "1"
            memory: "1.5Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
      restartPolicy: Always

      volumes:
      - name: config
        configMap:
          name: mediamtx-config
          defaultMode: 0644  # Ensure the file is readable