apiVersion: v1
kind: Service
metadata:
  name: mediamtx
spec:
  type: NodePort
  ports:
  - name: rtsp
    port: 8554
    targetPort: 8554
    protocol: TCP
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
  - name: web
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: web-rtc
    port: 8889
    targetPort: 8889
    protocol: TCP
  - name: rtsp-udp
    port: 8890
    targetPort: 8890
    protocol: UDP
  - name: udp-extra
    port: 8189
    targetPort: 8189
    protocol: UDP
  selector:
    app: mediamtx
