apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route-1
  namespace: default
spec:
  parentRefs:
  - name: api-gateway
    namespace: consul
  rules:
  - matches:
    - path:
        type: RegularExpression
        value: "/.*"
    backendRefs:
    - name: frontend
      kind: Service
  - matches:
    - path:
        type: RegularExpression
        value: "/api/Device/.*"
    backendRefs:
    - name: config-api
      kind: Service                                                                            
  - matches:
    - path:
        type: RegularExpression
        value: "/api/Component/.*"
    backendRefs:
    - name: config-api
  - matches:
    - path:
        type: RegularExpression
        value: "/api/Auth/.*"
    backendRefs:
    - name: auth-api
      kind: Service

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway 
spec:
  destination:
    name: config-api
  sources:
    - name: api-gateway
      permissions:
        - action: allow
          http:
            pathPrefix: /api/Device/
            methods: ['GET','POST'] 
    - name: fortio
      action: allow 
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: auth-intention 
spec:
  destination:
    name: auth-api
  sources:
    - name: api-gateway
      action: allow  
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend-intention 
spec:
  destination:
    name: frontend
  sources:
    - name: api-gateway
      action: allow 
    - name: fortio
      action: allow  
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: keycloak-intention 
spec:
  destination:
    name: keycloak
  sources:
    - name: auth-api
      action: allow  
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: postgres-intention 
spec:
  destination:
    name: postgres
  sources:
    - name: config-api
      action: allow  
# ---
# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceIntentions
# metadata:
#   name: fortio-intention 
# spec:
#   destination:
#     name: config-api
#   sources:
#     - name: fortio
#       action: allow 