version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ConfigDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - arc-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD_FILE=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=ConfigDb
      - DB_USER=postgres
      - DB_PASSWORD_FILE=admin
    networks:
      - arc-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
 #   healthcheck:
 #     test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
 #     interval: 30s
 #     timeout: 10s
 #     retries: 3
    depends_on:
      - postgres

  mediamtx:
    image: bluenviron/mediamtx
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.27.79
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    networks:
      - arc-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  #  healthcheck:
  #    test: ["CMD", "nc", "-z", "localhost", "8554"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 3

volumes:
  postgres_data:
  keycloak_data:
networks:
  arc-network:
    external: true
