global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'authentication-api'
    static_configs:
      - targets: ['authentication:8080']  # Adjust the port as needed

  - job_name: 'configuration-api'
    static_configs:
      - targets: ['configuration:8080']  # Adjust the port as needed

  - job_name: 'vpm'
    static_configs:
      - targets: ['vpm:8080']  # Adjust the port as needed

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']  # Adjust the port as needed
  
