apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-spa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-spa
  template:
    metadata:
      labels:
        app: web-spa
    spec:
      containers:
      - name: web-spa
        image: phadkesharanmatrixcomsec/arc-webspa:hls-1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: web-spa-service
spec:
  selector:
    app: web-spa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP